#!/usr/bin/env python3

import sys

from '../src/yonah_rqt.main_window' import MyPlugin
from rqt_gui.main import Main

plugin = 'yonah_rqt.main_window.MyPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
