#!/usr/bin/env python3

import sys

from '../src/rqt_mypkg.my_module' import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_mypkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
