#!/usr/bin/env python3

# Copyright (C) 2020 Rumesh Sudhaharan

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from inotify.adapters import Inotify

import rospy
from std_msgs.msg import String

if __name__ == '__main__':
	try:
		rospy.init_node("inotify_node", anonymous=False, disable_signals=True)

		file_modify_pub = rospy.Publisher("ogc/files/modified", String, queue_size=10)

		watch_dir = rospy.get_param("~watch_dir")

		adapater = Inotify()
		adapater.add_watch(watch_dir)

		move_from = []

		for event in adapater.event_gen(yield_nones=False):

			if event[1][0] == "IN_MOVED_FROM" and event[3][:11] == ".syncthing." and event[3][-4:] == ".tmp":
				move_from.append(event[3][11:-4])

			if event[1][0] == "IN_MOVED_TO":
				if event[3] in move_from:
					rospy.loginfo(event[3])
					file_modify_pub.publish(event[3])
					move_from.remove(event[3])


	except rospy.ROSInterruptException:
		exit()
	except KeyboardInterrupt:
		exit()
