#!/usr/bin/env python3

from inotify.adapters import Inotify

import rospy
from std_msgs.msg import String

if __name__ == '__main__':
	try:
		rospy.init_node("inotify_node", anonymous=False, disable_signals=True)

		file_modify_pub = rospy.Publisher("/ogc/filesystem/modified", String, queue_size=10)

		watch_dir = rospy.get_param("~watch_dir")

		adapater = Inotify()
		adapater.add_watch(watch_dir)

		move_from = []

		for event in adapater.event_gen(yield_nones=False):

			if event[1][0] == "IN_MOVED_FROM" and event[3][:11] == ".syncthing." and event[3][-4:] == ".tmp":
				move_from.append(event[3][11:-4])

			if event[1][0] == "IN_MOVED_TO":
				if event[3] in move_from:
					rospy.loginfo(event[3])
					file_modify_pub.publish(event[3])
					move_from.remove(event[3])


	except rospy.ROSInterruptException:
		exit()
	except KeyboardInterrupt:
		exit()
