#!/usr/bin/env python3

# Copyright (C) 2020 Rumesh Sudhaharan

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import rospy

from identifiers.srv import GetDetails

if __name__ == '__main__':
	rospy.init_node('identifiers_test_node', anonymous=False, disable_signals=True)

	rospy.wait_for_service("identifiers/get/number")
	rospy.wait_for_service("identifiers/get/imei")
	rospy.wait_for_service("identifiers/get/serial")

	try:
		get_number = rospy.ServiceProxy("identifiers/get/number", GetDetails)
		get_imei = rospy.ServiceProxy("identifiers/get/imei", GetDetails)
		get_serial = rospy.ServiceProxy("identifiers/get/serial", GetDetails)

		number_test = get_number(1)
		rospy.loginfo(number_test.data)

		imei_test = get_imei(1)
		rospy.loginfo(imei_test.data)

		serial_test = get_serial(1)
		rospy.loginfo(serial_test.data)

		number_test_2 = get_number(2)
		rospy.loginfo(number_test_2.data)

		imei_test_2 = get_imei(2)
		rospy.loginfo(imei_test_2.data)

		serial_test_2 = get_serial(2)
		rospy.loginfo(serial_test_2.data)

	except rospy.ServiceException as e:
		rospy.loginfo("Service call failed: " + e)

